auth_enabled: false

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318

ingester:
  trace_idle_period: 10s # Default is 10s
  max_block_bytes: 10485760 # 10 MB max size (Default is 524288000 = 500 MB)
  max_block_duration: 5m # Default is 30m

compactor:
  compaction:
    compacted_block_retention: 1h # Default is 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
