{
 "title": "token-tracker-demo",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tempo Traces",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "7640e587", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "token-tracker-service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(chat_request_latency_seconds_sum[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(chat_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    { "expression": "${A} / ${B}", "type": "math" }
   ]
  },
  {
   "title": "P95 Latency (s)",
   "type": "timeseries",
   "description": "95th percentile latency over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(chat_request_latency_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Total Tokens (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(chat_token_usage_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}